language: dart
dist: precise
dart:
  - stable
before_install:
  - export DISPLAY=:99.0
  - export PATH=$PATH":$PWD"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - pub run build_runner build
  - pub run dart_dev analyze
  - pub run dependency_validator --no-fatal-pins -i coverage, build, build_runner, build_web_compilers
  # run tests on dart2js output
  - pub run build_runner test -r -- -P dart2js
  # run tests on ddc output
  - pub run build_runner test -- -P dartdevc
