language: dart
dart:
  - stable
  - dev
script:
  - pub run build_runner build --delete-conflicting-outputs
  - git diff --exit-code
  - pub run dart_dev analyze
  # TODO: Remove ignore on analyzer once the wdesk ecosystem is all on a Dart 2 compat major version and we no longer need a "pinned" dep
  - pub run dependency_validator --no-fatal-pins -i analyzer,build_runner,build_web_compilers,built_value_generator
  - pub run dart_dev test

cache:
  directories:
   - $HOME/.pub-cache
   - $HOME/.dart_tool/build
