language: dart
dart:
  - stable
script:
  - pub run build_runner build
  - pub run dart_dev analyze
  # TODO: Remove ignore on analyzer once the wdesk ecosystem is all on a Dart 2 compat major version and we no longer need a "pinned" dep
  - pub run dependency_validator --no-fatal-pins -i coverage,build_web_compilers,analyzer
  # run tests on dart2js output
  - pub run build_runner test -- -P dartdevc
  # run tests on ddc output
  - pub run build_runner test -r -- -P dart2js
