builders:
  overReactBuilder:
    import: "package:over_react/src/builder/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".overReact.g.dart"]}
    auto_apply: all_packages 
    build_to: cache

targets:
  $default:
    sources:
#      include:
##        - "example/builder/**"
#        - "example/**"
#        - "lib/src/component/**"
      exclude:
        - ".dart_tool"
#        - "lib/src/builder/**"
#        - "lib/src/transformer/**"
#        - "test/over_react_builder_test.dart"
        - "test/component_files/**"
        - "test/gold_files/**"
        - "test/**"
    builders:
      built_value_generator|built_value:
        enabled: false
      built_redux|built_redux:
        enabled: false
        #over_react|overReactBuilder:
        #  enabled: true
        #  generate_for:
#          - "example/builder/props_mixin.dart"
#          - "lib/src/**"
#          - "test/component_files/**"
#          - "example/builder/basic.dart"


