builders:
  overReactBuilder:
    import: "package:over_react/src/builder/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".over_react.g.dart"]}
    auto_apply: all_packages
    build_to: cache

targets:
  $default:
    sources:
      exclude:
        # builder uses mirrors and will cause a build to fail if using build web compilers
        - "lib/src/builder/**"
        - "test/builder/**"

        # vm tests require the use of mirrors
        - "test/vm_tests/**"

        # has some faulty component declarations, might not need generation, but comment out for now cuz it breaks things
        - "test/over_react/component_declaration/transformer_helpers_test.dart"
