name: import_over_react_test
version: 0.0.1
description: Test importing over_react
environment:
  sdk: ">=1.19.1 <3.0.0"
dependencies:
  over_react:
    git:
      url: git://127.0.0.1:9000/
      ref: HEAD
dev_dependencies:
  dart_dev: ^2.0.0
  test: ">=0.12.36 <2.0.0"
