name: over_react_redux
version: 1.0.0
description: A wrapper for react-redux
authors:
  - Workiva UI Platform Chapter <uip@workiva.com>
  - Workiva App Frameworks Team <appframeworks@workiva.com>
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  collection: any
  js: any
  meta: any
  react: any
  redux: any
  over_react: any

dev_dependencies:
  build_resolvers: ^1.0.3
  build_runner: ^1.3.1
  build_test: ^0.10.6
  build_web_compilers: ^1.2.0
  over_react_test: ^2.5.0
  test: ^1.0.0
